name: Build and Deploy Node.js/Vue.js app to Azure Static Web Apps

on:
  push:
    branches:
      - test  # Remplacez "main" par la branche que vous souhaitez utiliser pour déclencher le déploiement

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Remplacez par la version de Node.js que vous utilisez

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 9df6867dc0f41302a470788bd5fc78249a5c4a2b5e4577d64800b896899455d75-5893b577-4621-4d9e-b3ce-7690589206e0003472592  # Créez ce secret dans votre dépôt GitHub
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Utilisé pour les vérifications de statut
          action: 'upload'
          app_location: '/'  # Dossier racine de l'application
          output_location: 'dist'  # Dossier où les fichiers construits sont situés (ajustez si nécessaire)
          api_location: ''  # Dossier de l'API si vous en avez une (laissez vide sinon)
