name: Deploy Backend

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      env:
        AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets['AZURE_CREDENTIALS_DEPLOYPROJECT' + matrix.env] }}
      uses: azure/webapps-deploy@v2
      with:
        app-name: myapp-backend-${{ matrix.env }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: target/*.jar

    strategy:
      matrix:
        env: [1, 2, 3]
      fail-fast: false
